### ISSUE TITLE
Built boot.img can't boot

### ISSUE THREAD

**Issue by bencejuhaasz** [cfig/Android_boot_image_editor#10]
After flashing the built boot img with modified kernel, it stops booting on the google logo. The kernel compiled without errors, so the problem is in these tools. It isn't working even with known working(newest elementalx for nexus5x) kernel image, because it can't pack correctly the boot img.

**Comment by cfig** [comment]
Be sure to unlock your device, our tool will re-pack boot.img with default keys, which is different from Nexus production keys.
Unlocked devices should display a small unlock icon below the google boot logo.

**Comment by bencejuhaasz** [comment]
It's already unlocked of course, and was unlocked on the day it arrived, never relocked.

**Comment by cfig** [comment]
I don't have Nexus5X at hand, but I had tried to flash new boot.img for N5X  before.
What I can suggest is to get official images from: 
https://developers.google.com/android/images#bullhead
And start hacking from here.

**Comment by cfig** [comment]
Close obsolete issue
