### ISSUE TITLE
error

### ISSUE THREAD

**Issue by depesh1977** [cfig/Android_boot_image_editor#113]
`test@Aspire-E5-722:~/boot_editor_r11$ ./gradlew clear
[main] WARN cfig.packable.PackableLauncher - [boot.img] will be handled by [BootImgParser]
[main] ERROR cfig.packable.PackableLauncher - command 'clear' can not be recognized
[main] INFO cfig.packable.PackableLauncher - available BootImgParser subcommands are:
[main] INFO cfig.packable.PackableLauncher - 	@footer
[main] INFO cfig.packable.PackableLauncher - 	capabilities
[main] INFO cfig.packable.PackableLauncher - 	flash
[main] INFO cfig.packable.PackableLauncher - 	pack
[main] INFO cfig.packable.PackableLauncher - 	pull
[main] INFO cfig.packable.PackableLauncher - 	unpack
`

**Comment by cfig** [comment]
Hope this info helps. Thanks.
