### ISSUE TITLE
Fix build error in gradle 8+

### ISSUE THREAD

**Issue by cfig** [cfig/Android_boot_image_editor#116]

**Comment by naz664** [comment]
Install jdk version 11+
**sudo apt-get install openjdk-17-jdk**
this should fix it

**Comment by cfig** [comment]
Thank you ~

With this commit https://github.com/cfig/Android_boot_image_editor/commit/95ee9b6d85d0f6222d1dfe2d44ccc3c2aab8d38d
it works fine.
Previously I set the compiling jdk to 17, but many guys are still using jdk 11. So I reverted that.
