### ISSUE TITLE
添加对合并dtb的支持

### ISSUE THREAD

**Issue by dsanke** [cfig/Android_boot_image_editor#134]
https://source.android.com/docs/core/architecture/dto/multiple?hl=zh-cn
现在很多机器的dtb是多合一的，工具直接用dtc去反编译只是获得了slot 0的dts
例如 红米 k50 ultra 的 dtb 在 vendor_boot 内
前4字节是 D0 0D FE ED，5-8 字节是 00 07 55 C0（这是第一份dtb的长度）
从0x755C0开始又是下一份dtb
[dtb.zip](https://github.com/cfig/Android_boot_image_editor/files/13807842/dtb.zip)
可以增加分割dtb并分别反编译为dts的功能

**Comment by cfig** [comment]
有完整的vendor_boot.img可以上传一份吗？

**Comment by cfig** [comment]
功能已提交，有问题及时反馈

**Comment by dsanke** [comment]
[vendor_boot.zip](https://github.com/cfig/Android_boot_image_editor/files/13873158/vendor_boot.zip)
这是完整的vendor_boot.img

1.unpack以后，不做改动，直接pack，再unpack，然后对比两次生成的build文件夹，每个dts都不一样，但dtb都一样
![1](https://github.com/cfig/Android_boot_image_editor/assets/2108751/f0a42db6-b15e-4bbb-961e-24a5d3548379)
![2](https://github.com/cfig/Android_boot_image_editor/assets/2108751/474f627a-49cb-40f1-95fa-fc23844ce825)
右侧是第一次unpack的，左侧是第二次unpack的
又试了下，把dts文件删掉以后再pack，不执行dts编译到dtb的过程，再去unpack，最终得到的dts就会和原来的dts一模一样
如果存在对应的dtb，不存在dts，个人认为应该视作正常情况，而不是提示找不到dts无法编译的fetal error

2.dtb.dts及dtb.dts.yaml没有必要生成出来，pack回去的时候也不用它

3.删掉dtb文件，留下数个dtb.*以后，再pack回去就不含dtb了，感觉检测dtb.*是否存在更合理

4.建议个位数编号前补0，这样更好区分每组文件

**Comment by cfig** [comment]
* dts 不一致问题：发现dtc的不同版本会导致反编译的dts不一致，但是最终给linux的dtb节点数值保持一致。不影响功能，忽略。
* 找了Pixel 8的vendor_kernel_boot.img, 有4份dtb；偶尔也有十多个dtb的。序号就不改了。
* pack： 如果不希望重新打包dtb, 可以删掉所有*.dts, 系统就会用原始的dtb。

重新提交了，修复了一个小问题，现在应该差不多了。

**Comment by dsanke** [comment]
我又检查了下，上游的dtc 1.6.1和1.7.0会造成问题，反编译的时候把hex转了字符串，编译的时候没能正确处理
1.6.0版本没有问题，反编译出来就是hex
![1](https://github.com/cfig/Android_boot_image_editor/assets/2108751/a6a416d4-b3cf-407a-b903-3d28d2388ad5)
在我的arch linux上，需要执行
`pacman -U https://archive.archlinux.org/packages/d/dtc/dtc-1.6.0-3-x86_64.pkg.tar.zst`
来降级dtc到1.6.0版本
然后编辑/etc/pacman.conf，添加
`IgnorePkg = dtc`
来忽略dtc的升级

**Comment by cfig** [comment]
感谢支持～
