### ISSUE TITLE
Failed unpacking boot.img

### ISSUE THREAD

**Issue by keren-gonen-wdc** [cfig/Android_boot_image_editor#142]
I am using Ubuntu 20.04.
I installed all the pre-reqs according to the readme.
Using Android14 boot image, I get the following (also added the debug output) - 
[fail.log](https://github.com/cfig/Android_boot_image_editor/files/14788127/fail.log)

> Configure project :lazybox
Path for java installation '/usr/lib/jvm/openjdk-17' (Common Linux Locations) does not contain a java executable

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':lazybox'.
> Failed to calculate the value of task ':lazybox:compileJava' property 'javaCompiler'.
   > Cannot find a Java installation on your machine matching this tasks requirements: {languageVersion=11, vendor=any, implementation=vendor-specific} for LINUX on x86_64.
      > No locally installed toolchains match and toolchain download repositories have not been configured.

* Try:
> Learn more about toolchain auto-detection at https://docs.gradle.org/8.7-rc-3/userguide/toolchains.html#sec:auto_detection.
> Learn more about toolchain repositories at https://docs.gradle.org/8.7-rc-3/userguide/toolchains.html#sub:download_repositories.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Failed to query the value of property 'buildFlowServiceProperty'.
> Could not isolate value org.jetbrains.kotlin.gradle.plugin.statistics.BuildFlowService$Parameters_Decorated@7ce0f4ec of type BuildFlowService.Parameters
   > A problem occurred configuring project ':lazybox'.
      > Failed to calculate the value of task ':lazybox:compileJava' property 'javaCompiler'.
         > Cannot find a Java installation on your machine matching this tasks requirements: {languageVersion=11, vendor=any, implementation=vendor-specific} for LINUX on x86_64.
            > No locally installed toolchains match and toolchain download repositories have not been configured.

* Try:
> Learn more about toolchain auto-detection at https://docs.gradle.org/8.7-rc-3/userguide/toolchains.html#sec:auto_detection.
> Learn more about toolchain repositories at https://docs.gradle.org/8.7-rc-3/userguide/toolchains.html#sub:download_repositories.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Thanks

**Comment by cfig** [comment]
Hi, 
Do you have a proper jdk installed?\
log says:
>  Path for java installation '/usr/lib/jvm/openjdk-17' (Common Linux Locations) does not contain a java executable

Did you try "sudo apt install openjdk-17-jdk" ?

**Comment by keren-gonen-wdc** [comment]
Just tried the install command, but I get this - openjdk-17-jdk is already the newest version (17.0.10+7-1~20.04.1)

**Comment by shaquibimdad** [comment]
I am having the same issue

**Comment by shaquibimdad** [comment]
❯ ./gradlew unpack

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':lazybox'.
> Failed to calculate the value of task ':lazybox:compileJava' property 'javaCompiler'.
   > Cannot find a Java installation on your machine matching this tasks requirements: {languageVersion=11, vendor=any, implementation=vendor-specific} for LINUX on x86_64.
      > No locally installed toolchains match and toolchain download repositories have not been configured.

**Comment by shaquibimdad** [comment]
[Resetting head to this commit tmp fixes this issue](https://github.com/cfig/Android_boot_image_editor/commit/afc0eabc32a35c1353bc07c3f2c5861d4f10064a)

**Comment by cfig** [comment]
> [Resetting head to this commit tmp fixes this issue](https://github.com/cfig/Android_boot_image_editor/commit/afc0eabc32a35c1353bc07c3f2c5861d4f10064a)

Hi @shaquibimdad , thanks for finding this ~
It may be caused by the improper setting in gradle build file.
Do you have a chance to try latest commit from "rc" branch?

**Comment by shaquibimdad** [comment]
> > [Resetting head to this commit tmp fixes this issue](https://github.com/cfig/Android_boot_image_editor/commit/afc0eabc32a35c1353bc07c3f2c5861d4f10064a)
> 
> Hi @shaquibimdad , thanks for finding this ~ It may be caused by the improper setting in gradle build file. Do you have a chance to try latest commit from "rc" branch?

![image](https://github.com/cfig/Android_boot_image_editor/assets/36896950/8b4a724a-b7a0-4f2e-85b3-5b68c2cbc600)

I can confirm it is working fine

**Comment by cfig** [comment]
Thank you @shaquibimdad and @keren-gonen-wdc  ~
