### ISSUE TITLE
`pack` task not working for dtbo load offset value `0xffffffff80000000`

### ISSUE THREAD

**Issue by erawhctim** [cfig/Android_boot_image_editor#18]
Getting an error trying to re-pack and unpacked `boot.img` from stock Motorola Moto X firmware:
```
java.lang.NumberFormatException: For input string: "ffffffff80000000"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:592)
        at cfig.UnifiedConfig.toArgs(UnifiedConfig.kt:64)
        at cfig.Packer.pack(Packer.kt:238)
        at cfig.RKt.main(R.kt:10)
```

The relevant`bootimg.json` section:
```
"recoveryDtbo" : {
    "file" : null,
    "position" : "0x680800",
    "size" : "0x0",
    "loadOffset" : "0xffffffff80000000"
  }
```

Not sure if this is due to the phone/firmware (and thus not possible) or fixable with a code enhancement. Happy to help if I can! Just don't really know anything about the `boot.img` format.

**Comment by cfig** [comment]
Dear erawhctim, 
Could you please attach your boot.img?
Or paste the image link?

Thanks

**Comment by erawhctim** [comment]
[test boot imgs.zip](https://github.com/cfig/Android_boot_image_editor/files/2068449/test.boot.imgs.zip)

Sure thing:
* `TMO_RETAIL_XT1053_4.4.3-KXA21.12-L1.21_MR4_CFC` and `XT1053_GHOST_TMO-RETAIL-US_5.1_LPA23.12-15_cid9_CFC` came from the motorola firmware site (don't have the link anymore but I could find it again)
* `XT1053_5.1_RETUS_Untouched` was a repost of a retail rom from XDA Developers. All are for the motorola moto x (2013) T-Mobile version

Doing some more googling I found out apparently motorola has their own version of fastboot that is needed for some devices? Not sure if that's needed here or if that's why the `boot.img` format is different than your test file for the N5

**Comment by cfig** [comment]
Dear erawhctim,
I can fix the 'unpack' issue, but seems the image didn't follow AOSP signing style.
The image has a size of 10MB, but I can only recognize about ~6MB of them.
Image has paddings of 0xff, and private footer.

> 09fff50: ffff ffff ffff ffff ffff ffff ffff ffff  ................
> 09fff60: ffff ffff ffff ffff ffff ffff ffff ffff  ................
> 09fff70: ffff ffff ffff ffff ffff ffff ffff ffff  ................
> 09fff80: ffff ffff ffff ffff ffff ffff ffff ffff  ................
> 09fff90: ffff ffff ffff ffff ffff ffff ffff ffff  ................
> 09fffa0: ffff ffff ffff ffff ffff ffff ffff ffff  ................
> 09fffb0: ffff ffff ffff ffff ffff ffff ffff ffff  ................
> 09fffc0: 4355 5354 4f4d 4552 2055 5341 556e 6c6f  CUSTOMER USAUnlo
> 09fffd0: 636b 6162 6c65 0000 0000 0000 0000 0000  ckable..........
> 09fffe0: 4d4f 545f 4150 3235 3600 0000 0000 0000  MOT_AP256.......
> 09ffff0: 0000 0000 0000 0000 0000 0000 0000 0900  ................
> 0a00000: 0a                                       .

Sorry for that.

**Comment by erawhctim** [comment]
ahh ok I see - so does that mean the modified `boot.img` that is output from the `pack` task is a different size/layout from the original since the format is not standard?

**Comment by cfig** [comment]
Yes it's not recommended to flash the modified boot.img back to your phone.
And this project will not try to parse private/proprietary formats.

I will record the device model on incompatible list.

**Comment by erawhctim** [comment]
Got it - thanks for the heads up!
