### ISSUE TITLE
Nexus 6p stucks in boot after flash the boot.img

### ISSUE THREAD

**Issue by ikey4u** [cfig/Android_boot_image_editor#21]
Hi, I use this tool to unpack factory boot.img pulled from the Nexus 6P, and use fastboot to flash the modified boot.img(I only changed `ro.secure=0 and ro.debuggable=1` in build/unzip_boot/root/default.prop).  Then when I reboot Nexus, it loops boot between the unlocked warning page and Google logo page.

**Comment by cfig** [comment]
Sorry I don't have N6p at hand.
Maybe you can try to unpack and pack the original boot.img without modifying anything?
If this works fine, then you can modify something like default.prop.

**Comment by ikey4u** [comment]
@cfig  Thank you for your kind reply

**Comment by cfig** [comment]
Close obsolete bug, if more questions, please comment.
Thanks.
