### ISSUE TITLE
有没有可能支持私钥签名呢？

### ISSUE THREAD

**Issue by youyim** [cfig/Android_boot_image_editor#27]
> RSA public key的生成
除了这些 descriptor 之外，auxiliary data block 中还有一个重要的信息，就是 RSA public key。这个 public key 将被用来校验 authentication data block 中的 signature data。
在 avbtool make_vbmeta_image 时，必须用--key参数来指定生成 signature data 的 RSA private key，AOSP external/avb/test/data 目录下有各种供测试使用 RSA private key，格式为 PEM。avbtool 会根据 RSA private key 提取 public key 并加上 RSA key 的 header 打包进 auxiliary data block。
可以通过avbtool extract_public_key --key ***.pem --output ***.avbpubkey 来生成的 public key。

有办法从vbmeta.img里提取到xxx.avbpubkey，能否通过xxx.avbpubkey计算出私钥xxx.pem？

> 'SHA256_RSA2048': Algorithm(
        algorithm_type=1,        # AVB_ALGORITHM_TYPE_SHA256_RSA2048
        hash_num_bytes=32,
        signature_num_bytes=256,
        public_key_num_bytes=8 + 2*2048/8,
        padding=[
            # PKCS1-v1_5 padding
            0x00, 0x01] + [0xff]*202 + [0x00] + [
                # ASN.1 header
                0x30, 0x31, 0x30, 0x0d, 0x06, 0x09, 0x60, 0x86,
                0x48, 0x01, 0x65, 0x03, 0x04, 0x02, 0x01, 0x05,
                0x00, 0x04, 0x20,
            ]),

在添加--algorithm SHA256_RSA2048后他也会直接把--key xxx.pem生成为

> public_key_num_bytes=8 + 2*2048/8

一个520bytes的xxx.avbpubkey
或者在生成vbmeta.img不使用--algorithm SHA256_RSA***、--key ***.pem而是直接使用xxx.avbpubkey呢？

这是vivo NEX，使用私钥生成的vbmeta.img，提取出的vivo.avbpubkey
[NEX.zip](https://github.com/cfig/Android_boot_image_editor/files/3133733/NEX.zip)

**Comment by cfig** [comment]
> 有办法从vbmeta.img里提取到xxx.avbpubkey，能否通过xxx.avbpubkey计算出私钥xxx.pem？

No, pub key->private key这个不可行

> 或者在生成vbmeta.img不使用--algorithm SHA256_RSA***、--key ***.pem而是直接使用xxx.avbpubkey呢？

"--key"后面要用私钥，"SHA256_XXX"表示hash算法，参数不可少啊
