### ISSUE TITLE
dtbo.img unpack

### ISSUE THREAD

**Issue by 18712886438** [cfig/Android_boot_image_editor#28]
老哥,能不能支持一下 dtbo解包呢, 我现在只能是编译内核,把带dtb的zImage塞进去

**Comment by cfig** [comment]
#### v2的boot image header已经支持dtb了，你无须提前把zImage和dtb打包在一起。前提是bootloader支持v2格式。另外里面的dtbo是给recovery用的，不是给normal mode用的。
如下
https://github.com/cfig/Android_boot_image_editor/blob/master/doc/layout.md

|--------------------------------+--------------------------|    --> 1648 (0x670)
|<dtb  length>            [v2]   |     4                    |
|--------------------------------+--------------------------|    --> 1652
|<dtb  offset>            [v2]   |     8                    |
|--------------------------------+--------------------------|    --> 1660 (0x67c)

**Comment by cfig** [comment]
难道你想要解dtbo.img?有啥推荐的工具？fdtdump貌似不好使

**Comment by 18712886438** [comment]
> 难道你想要解dtbo.img?有啥推荐的工具？fdtdump貌似不好使

我也没找到啥好的工具,就暂时先用我上面说的办法凑合过日子

**Comment by cfig** [comment]
找到了
看这个mkdtimg, 可以create/dump dtbo.img.
https://android-review.googlesource.com/c/platform/system/libufdt/+/347649

**Comment by 18712886438** [comment]
> 找到了
> 看这个mkdtimg, 可以create/dump dtbo.img.
> https://android-review.googlesource.com/c/platform/system/libufdt/+/347649

哦哦  好的好的, 我看看去
