### ISSUE TITLE
Invalid NativePlatform: linux_aarch64

### ISSUE THREAD

**Issue by OPPO9008** [cfig/Android_boot_image_editor#33]
root@localhost:/home/serval# cd Android_boot_image_editor
root@localhost:/home/serval/Android_boot_image_editor# ./gradlew unpack                   

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':aosp:mkbootfs'.
> Exception thrown while executing model rule: NativeComponentModelPlugin.Rules#createBinaries(Targete
dNativeComponentInternal, PlatformResolvers, BuildTypeContainer, FlavorContainer, ServiceRegistry)
   > Invalid NativePlatform: linux_aarch64

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
 output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

**Comment by cfig** [comment]
Hi,
Are U running it on arm64+linux laptop? Or on some dev boards?
Can you list the type details of your host machine?

Thanks.

**Comment by OPPO9008** [comment]
i use android chroot Ubuntu 16.04.6 LTS (Xenial Xerus) ，device name is redmi 5. kernel 3.18.140.
login by ssh

**Comment by cfig** [comment]
Seems some modification in build.gradle is needed to compile 'mkbootfs' on aarch64-linux.
I will try to get a similar platform with same arch, but not sure.
If you do need it on your phone, you can try: 
(1) remove build dependencies of 'mkbootfs' in gradle files.
(2) compile 'mkbootfs' manually and put it to desired place, a.k.a "./aosp/mkbootfs/build/exe/mkbootfs/mkbootfs"
(3) ...

**Comment by cfig** [comment]
Hi,
Could you have a try with latest dev branch? I replace build.gradle with makefile for c/cpp compilation, this is more convenient for embedded development.

    usage:
        make
        ./gradlew unpack
        ./gradlew pack

"make" will patch some local files, and compile c/cpp. After this, you can run the commands in README.

Thanks.

**Comment by cfig** [comment]
I verified dev branch on x86_64/linux and Raspbian(arm-v7/linux).
Be sure to install gcc/g++.
