### ISSUE TITLE
An error was encountered while packaging the boot image.

### ISSUE THREAD

**Issue by gesangtome** [cfig/Android_boot_image_editor#38]
[main] WARN cfig.packable.PackableLauncher - [boot.img] will be handled by [BootImgParser]
[main] WARN cfig.packable.PackableLauncher - 'pack' sequence initialized
[main] INFO Packer - Loading config from build/unzip_boot/bootimg.json
[main] INFO Packer - Deleting boot.img.google ...
[main] INFO Packer - Deleting boot.img.clear ...
[main] INFO Packer - Writing data ...
[main] INFO Packer - [./aosp/system/tools/mkbootimg/mkbootimg.py, --header_version, 1, --base, 0x0, --kernel, build/unzip_boot/kernel, --kernel_offset, 0x8000, --ramdisk_offset, 0x1000000, --pagesize, 4096, --cmdline, console=ttyMSM0,115200n8 earlycon=msm_geni_serial,0xa90000 androidboot.hardware=qcom androidboot.console=ttyMSM0 androidboot.memcg=1 lpm_levels.sleep_disabled=1 video=vfb:640x400,bpp=32,memsize=3072000 msm_rtb.filter=0x237 service_locator.enable=1 swiotlb=2048 firmware_class.path=/vendor/firmware_mnt/image loop.max_part=7 androidboot.usbcontroller=a600000.dwc3 buildvariant=user, --os_version, 9.0.0, --os_patch_level, 2019-06-00, --tags_offset, 0x100, --id, --output, boot.img.google]
0xcb57d6c13883d5502180dc12992c4033224f97e1000000000000000000000000
[main] INFO Packer - ours hash b9fa59f6d31da829780b142e6070823548eeac39, google's hash 7aae740b6dbd08cc5ace9efea8d98131669964ec
[main] ERROR Packer - Hash verification failed
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:106)
        at cfig.packable.PackableLauncherKt.main(PackableLauncher.kt:92)
Caused by: java.lang.UnknownError: Do not know why hash verification fails, maybe a bug
        at cfig.Packer.pack(Packer.kt:169)
        at cfig.packable.BootImgParser.pack(BootImgParser.kt:72)
        ... 8 more

FAILURE: Build failed with an exception.

Hello. This tool tells me that my boot image hash is different from google, and then returns a non-zero exit value. How can I skip this error?

**Comment by cfig** [comment]
Hi,

You can skip the error with following patch:

```
diff --git a/bbootimg/src/main/kotlin/bootimg/Packer.kt b/bbootimg/src/main/kotlin/bootimg/Packer.kt
index a8bb154..a774b0d 100644
--- a/bbootimg/src/main/kotlin/bootimg/Packer.kt
+++ b/bbootimg/src/main/kotlin/bootimg/Packer.kt
@@ -166,7 +166,7 @@ class Packer {
             log.info("Hash verification passed: ${Helper.toHexString(ourHash)}")
         } else {
             log.error("Hash verification failed")
-            throw UnknownError("Do not know why hash verification fails, maybe a bug")
+            //throw UnknownError("Do not know why hash verification fails, maybe a bug")
         }
     }
 }

```

But maybe there is something wrong, can you attach you boot.img here? Then I can have a check.

**Comment by gesangtome** [comment]
![boot tar xz](https://user-images.githubusercontent.com/9876749/82176901-a2e71f80-990a-11ea-9346-7d93cffde344.png)

This attachment is an XZ compressed document, but the suffix '.png' is artificially added, because github does not support files with the .img suffix

**Comment by cfig** [comment]
Found the cause, It's not a problem indeed.
You can just remove the line "throw UnknownError(...)" and proceed.
I will submit a fix later.

**Comment by gesangtome** [comment]
@cfig Thanks

**Comment by cfig** [comment]
Please have a try with latest master branch, it should work.

**Comment by gesangtome** [comment]
@cfig nice work!
