### ISSUE TITLE
Hello, is there a Windows version?

### ISSUE THREAD

**Issue by QSJHUA** [cfig/Android_boot_image_editor#40]
Hello, is there a Windows version? Looking forward to the Windows version

**Comment by cfig** [comment]
Hi,
This tool needs some external tools like "cpio", etc. I may have a try
later.
If you are interested in it, Windows porting patches are welcome :)

**Comment by cfig** [comment]
'cpio' dependency is removed in dev branch. But there are still many other *nix specific stuff.

**Comment by cfig** [comment]
latest Windows 10 now has symbolic links, there maybe a chance to port the *nix cpio/mkbootfs to Win. 
https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/

Other problems *may* include: external python/openssl/xz/lz4.. .

**Comment by cfig** [comment]
Windows version works now.
