### ISSUE TITLE
gradlew unpack ERROR

### ISSUE THREAD

**Issue by scarlet-glass** [cfig/Android_boot_image_editor#45]
**ERROR LOG :**

Downloading https://services.gradle.org/distributions/gradle-6.4.1-bin.zip
.........10%..........20%..........30%..........40%.........50%..........60%..........70%..........80%.........90%..........100%

Welcome to Gradle 6.4.1!

Here are the highlights of this release:
 - Support for building, testing and running Java Modules
 - Precompiled script plugins for Groovy DSL
 - Single dependency lock file per project

For more details see https://docs.gradle.org/6.4.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Task :bbootimg:compileKotlin
w: /home/ubuntu/12334/Android_boot_image_editor/bbootimg/src/main/kotlin/avb/Avb.kt: (199, 27): Variable 'descriptors' initializer is redundant
w: /home/ubuntu/12334/Android_boot_image_editor/bbootimg/src/main/kotlin/avb/desc/HashDescriptor.kt: (78, 13): Variable 'digest' is never used
w: /home/ubuntu/12334/Android_boot_image_editor/bbootimg/src/main/kotlin/init/Reboot.kt: (21, 30): Parameter 'cmd' is never used
w: /home/ubuntu/12334/Android_boot_image_editor/bbootimg/src/main/kotlin/init/Reboot.kt: (21, 60): Parameter 'rebootTarget' is never used

> Task :aosp:mkbootfs.10:compileMkbootfsExecutableMkbootfsCpp FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':aosp:mkbootfs.10:compileMkbootfsExecutableMkbootfsCpp'.
> No tool chain is available to build for platform 'linux_x86-64':
    - Tool chain 'visualCpp' (Visual Studio):
        - Visual Studio is not available on this operating system.
    - Tool chain 'gcc' (GNU GCC):
        - Could not find C compiler 'gcc' in system path.
    - Tool chain 'clang' (Clang):
        - Could not find C compiler 'clang' in system path.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 5m 58s
5 actionable tasks: 5 executed

**Comment by cfig** [comment]
please install clang/gcc compiler first 

`sudo apt install clang`
