### ISSUE TITLE
解包时出现问题

### ISSUE THREAD

**Issue by kidachiP** [cfig/Android_boot_image_editor#48]
kiyoi@kiyoi-PC:~/Android_boot_image_editor$ ./gradlew unpack

> Task :bbootimg:compileKotlin FAILED
e: /home/kiyoi/Android_boot_image_editor/bbootimg/src/main/kotlin/bootimg/cpio/AndroidCpio.kt: (234, 33): Unresolved reference: readAllBytes
e: /home/kiyoi/Android_boot_image_editor/bbootimg/src/main/kotlin/bootimg/cpio/AndroidCpio.kt: (235, 30): Overload resolution ambiguity: 
public inline fun String(stringBuffer: StringBuffer): String defined in kotlin.text
public inline fun String(stringBuilder: StringBuilder): String defined in kotlin.text
public inline fun String(bytes: ByteArray): String defined in kotlin.text
public inline fun String(chars: CharArray): String defined in kotlin.text
e: /home/kiyoi/Android_boot_image_editor/bbootimg/src/main/kotlin/bootimg/cpio/AndroidCpio.kt: (242, 44): Overload resolution ambiguity: 
public inline fun String(stringBuffer: StringBuffer): String defined in kotlin.text
public inline fun String(stringBuilder: StringBuilder): String defined in kotlin.text
public inline fun String(bytes: ByteArray): String defined in kotlin.text
public inline fun String(chars: CharArray): String defined in kotlin.text
e: /home/kiyoi/Android_boot_image_editor/bbootimg/src/main/kotlin/bootimg/cpio/AndroidCpio.kt: (243, 56): Overload resolution ambiguity: 
public inline fun String(stringBuffer: StringBuffer): String defined in kotlin.text
public inline fun String(stringBuilder: StringBuilder): String defined in kotlin.text
public inline fun String(bytes: ByteArray): String defined in kotlin.text
public inline fun String(chars: CharArray): String defined in kotlin.text

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bbootimg:compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
1 actionable task: 1 executed

**Comment by cfig** [comment]
请安装Java 9以上版本试下，应该就好了～
