### ISSUE TITLE
gradlew unpack error

### ISSUE THREAD

**Issue by scarlet-glass** [cfig/Android_boot_image_editor#50]
system： Ubuntu 20.04
log：
 
./gradlew unpack

> Task :unpack
[main] WARN cfig.packable.PackableLauncher - [boot.img] will be handled by [BootImgParser]
[main] WARN cfig.packable.PackableLauncher - 'unpack' sequence initialized
[main] INFO cfig.packable.BootImgParser - header version 2
[main] WARN cfig.bootimg.v2.BootHeaderV2 - BootImgHeader constructor
[main] INFO cfig.Avb - python aosp/avb/avbtool.v1.2.py verify_image --image boot.img
[main] ERROR cfig.packable.BootImgParser - boot.img failed integrity check by "python aosp/avb/avbtool.v1.2.py verify_image --image boot.img"
[main] ERROR cfig.packable.BootImgParser - Parser can not continue
[main] WARN cfig.packable.PackableLauncher - 'unpack' sequence completed

BUILD SUCCESSFUL in 3s
13 actionable tasks: 1 executed, 12 up-to-date

**Comment by cfig** [comment]
Hi @scarlet-glass,
Log says:
```
[main] ERROR cfig.packable.BootImgParser - boot.img failed integrity check 
by "python aosp/avb/avbtool.v1.2.py verify_image --image boot.img"
```
Your boot.img failed integrity check?
Would you mind attaching your boot.img here?

**Comment by scarlet-glass** [comment]
@cfig 
recovery.img : https://wwa.lanzous.com/itzF9l7m5ni

**Comment by scarlet-glass** [comment]
我使用的Linux的Windows子系统，Ubuntu 20.04

**Comment by cfig** [comment]
手动试一下
python aosp/avb/avbtool.v1.2.py verify_image --image boot.img
看看成功否？
其实 你的recovery.img不用改名字，直接用recovery.img也可以，程序能认出来。
PS：目录下只能保留一个boot.img或者recovery.img, 否则程序找到一个支持的image之后，就不去找其他的了。

**Comment by cfig** [comment]
> 手动试一下
> python aosp/avb/avbtool.v1.2.py verify_image --image boot.img
> 看看成功否？
> 其实 你的recovery.img不用改名字，直接用recovery.img也可以，程序能认出来。
> PS：目录下只能保留一个boot.img或者recovery.img, 否则程序找到一个支持的image之后，就不去找其他的了。

最近太忙，回头闲了考虑把avbtool verify的依赖去掉。

**Comment by scarlet-glass** [comment]
@cfig 什么时候可以支持AVB3的解包？

**Comment by cfig** [comment]
> @cfig 什么时候可以支持AVB3的解包？

AVB3? 现在最新的才AVB v1.2吧.
boot image最新是v4(Android S or later). 
目前boot.img支持到v3.

**Comment by scarlet-glass** [comment]
> > @cfig 什么时候可以支持AVB3的解包？
> 
> AVB3? 现在最新的才AVB v1.2吧.
> boot image最新是v4(Android S or later).
> 目前boot.img支持到v3(Android R).

可是我解包直接报错啊。
----------------------------------------
`scarlet-glass@scarlet-glass-PC:~/Android_boot$ ./gradlew unpack
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :bbootimg:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bbootimg:compileKotlin'.
> Couldn't delete stale output file

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
1 actionable task: 1 executed
`

**Comment by scarlet-glass** [comment]
好像是我本地文件权限的问题，我已经解决了。确实可以解包V3的，感谢

**Comment by cfig** [comment]
感谢支持!
WSL下面运行貌似有问题(gradle problem?)，我只能跑编译好的版本.

Thanks and Happy Chinese New Year!

**Comment by scarlet-glass** [comment]
Hi @cfig 
这个工具在linux环境下解包时，输出的打印信息部分显示？？？，不会显示中文，是。gradlew文件编码格式的问题吗？

**Comment by cfig** [comment]
linux没见过，windows下倒是经常有。难道你的linux不支持utf8？
`locale`一下看看？
