### ISSUE TITLE
macOS Catalina FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by maps233-kk** [cfig/Android_boot_image_editor#51]
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :bbootimg:compileKotlin FAILED
e: /Users/maps-pc/Downloads/Android_boot_image_editor-master/bbootimg/src/main/kotlin/bootimg/cpio/AndroidCpio.kt: (251, 33): Unresolved reference: readAllBytes
e: /Users/maps-pc/Downloads/Android_boot_image_editor-master/bbootimg/src/main/kotlin/bootimg/cpio/AndroidCpio.kt: (252, 30): Overload resolution ambiguity: 
public inline fun String(stringBuffer: StringBuffer): String defined in kotlin.text
public inline fun String(stringBuilder: StringBuilder): String defined in kotlin.text
public inline fun String(bytes: ByteArray): String defined in kotlin.text
public inline fun String(chars: CharArray): String defined in kotlin.text
e: /Users/maps-pc/Downloads/Android_boot_image_editor-master/bbootimg/src/main/kotlin/bootimg/cpio/AndroidCpio.kt: (259, 44): Overload resolution ambiguity: 
public inline fun String(stringBuffer: StringBuffer): String defined in kotlin.text
public inline fun String(stringBuilder: StringBuilder): String defined in kotlin.text
public inline fun String(bytes: ByteArray): String defined in kotlin.text
public inline fun String(chars: CharArray): String defined in kotlin.text
e: /Users/maps-pc/Downloads/Android_boot_image_editor-master/bbootimg/src/main/kotlin/bootimg/cpio/AndroidCpio.kt: (260, 56): Overload resolution ambiguity: 
public inline fun String(stringBuffer: StringBuffer): String defined in kotlin.text
public inline fun String(stringBuilder: StringBuilder): String defined in kotlin.text
public inline fun String(bytes: ByteArray): String defined in kotlin.text
public inline fun String(chars: CharArray): String defined in kotlin.text

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bbootimg:compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
1 actionable task: 1 executed

**Comment by cfig** [comment]
Can you please run `./gradlew unpack --scan` and paste the last line of the running result?

**Comment by cfig** [comment]
" Overload resolution ambiguity:" this is caused by obsolete java version.
Please update your java to JDK9 or later.
Thank you

**Comment by cfig** [comment]
I have verified on Catalina and BigSur. Thank U~
