### ISSUE TITLE
关于支持boot-gki.img解包问题

### ISSUE THREAD

**Issue by scarlet-glass** [cfig/Android_boot_image_editor#56]
我提取了ROM中的boot-gki.img文件，使用win下的工具解包时报错：

`PS E:\linux\boot_editor_r11> .\gradlew unpack
[main] WARN cfig.packable.PackableLauncher - No handler is activated, DO NOTHING!
PS E:\linux\boot_editor_r11>`

大神可以支持解包这个文件吗？

**Comment by cfig** [comment]
码农而已，大神是我等用来膜拜的～

是公开的ROM吗？有的话给个链接，我试试

**Comment by scarlet-glass** [comment]
> 码农而已，大神是我等用来膜拜的～
> 
> 是公开的ROM吗？有的话给个链接，我试试

这个好像是线刷包里面的，卡刷包里面么有这个东西。。大神有邮箱没有，我把这个img发给你

**Comment by cfig** [comment]
yuyezhong@gmail.com

**Comment by cfig** [comment]
本质上还是boot image.
改名成boot.img再解吧。Pixel手机的factory ROM里貌似没用这个名字。

**Comment by scarlet-glass** [comment]
果然是诶，这是为了迷惑用的吗。。。

**Comment by cfig** [comment]
哈
