### ISSUE TITLE
upddate dtbo.img hash into vbmeta.img?

### ISSUE THREAD

**Issue by 99degree** [cfig/Android_boot_image_editor#64]
as title, any chance to do so?

**Comment by cfig** [comment]
dtbo.img unpack/pack is not well tested. I can refine it later if I have time.

For now, as a workaround, if you modified dtbo.img, you can simply remove 'dtbo' from 'hashDescriptors' section  inside vbmeta.avb.json, and repack it.

**Comment by 99degree** [comment]
thx thumbs up for your great afford!
