### ISSUE TITLE
"Invalid NativePlatform: linux_aarch64"

### ISSUE THREAD

**Issue by DUOLabs333** [cfig/Android_boot_image_editor#69]
It seems that it doesn't work for arm64 hosts. There seems to be an issue about this #33, but the files that fixed the issue was removed.

**Comment by DUOLabs333** [comment]
I then tried to use a 64-bit chroot, but it failed with "A problem occurred starting process 'Gradle build daemon'".

**Comment by cfig** [comment]
Previously I borrowed a linux_aarch64 platform from a friend to verify basic features, but the nice guy left ~~
I can update the binary release of this tool, but may not have a chance to verify it.

**Comment by cfig** [comment]
Hi @DUOLabs333 ,
Can you help a try with latest 'bin" branch? This branch only has prebuilt files. Hopefully it should work.

**Comment by DUOLabs333** [comment]
It works for me. Thanks!

**Comment by cfig** [comment]
Good to hear :)
