### ISSUE TITLE
Kernel is not runnable after extraction

### ISSUE THREAD

**Issue by DUOLabs333** [cfig/Android_boot_image_editor#70]
This is a problem with Google's own `unpackbootimg`, so I don't know how much of this can be solved. I want to extract the Android kernel from boot.img of the Pixel 5A (found [here](https://developers.google.com/android/images) ), but for some reason, after extraction, the kernel won't work in QEMU.

**Comment by DUOLabs333** [comment]
`unlz4` has no effect.

**Comment by cfig** [comment]
Hi,
I downloaded "barbet-rd2a.210905.002-factory-923343d0.zip" from that page, version:  11.0.0 (RD2A.210905.002, Sep 2021).
After "unpack", the kernel is located at "build/unzip_boot/kernel", which is lz4 compressed, and I can `unlz4` it.
md5hash of files
```
c2466244f6b9bdd12c5c80d62ce1902f  build/unzip_boot/kernel
```
