### ISSUE TITLE
Can you add the clean command of the tool?

### ISSUE THREAD

**Issue by zhengjingjian** [cfig/Android_boot_image_editor#79]
Hi,you made a good job for us.Now I can modify the img files of andorid 11 easily.

If I need to modify a new file,I have to delete the old files manual.I think the command id very necessary。

**Comment by cfig** [comment]
OK, that's reasonable.

**Comment by cfig** [comment]
Hi,
Code updated, now you can have a try
```
gradle clean
```
or 
```
./gradlew clean
```

**Comment by zhengjingjian** [comment]
Thank you!It is awesome！
