### ISSUE TITLE
rk3566 Android 11 tablet

### ISSUE THREAD

**Issue by dieselnutjob** [cfig/Android_boot_image_editor#85]
Hi
I am trying to change the kernel image on an Android 11 tablet which has a an rk3566 SoC.
I used dd to dump the boot partition as a .img file.
I then did an unpack, and then a pack, but without modifying anyway, but the tablet boot loops with the boot partition overwritten with the the boot.img.signed2 output file (I guess that this is one to use).
Here are my output logs:-

Unpack
`
11:15:31:140 WARN PackableLauncher - [boot.img] will be handled by [BootImgParser]
11:15:31:228 WARN PackableLauncher - 'unpack' sequence initialized
11:15:31:236 INFO BootImgParser - header version 2
11:15:31:243 WARN BootHeaderV2 - BootImgHeader constructor
11:15:31:261 INFO Avb - python aosp/avb/avbtool.v1.2.py verify_image --image boot.img
Verifying image boot.img using embedded public key
vbmeta: Successfully verified footer and NONE vbmeta struct in boot.img
boot: Successfully verified sha256 hash of boot.img for image of 102600704 bytes
11:15:32:055 INFO KernelExtractor - [aosp/build/tools/extract_kernel.py, --input, build/unzip_boot/kernel, --output-configs, build/unzip_boot/kernel_configs.txt, --output-version, build/unzip_boot/kernel_version.txt]
11:15:32:060 INFO KernelExtractor - kernel version: [4.19.193]
11:15:32:060 INFO KernelExtractor - kernel config dumped to : build/unzip_boot/kernel_configs.txt
11:15:34:152 INFO ZipHelper - decompress(gz) done: build/unzip_boot/ramdisk.img.gz -> build/unzip_boot/ramdisk.img
11:15:34:154 INFO AndroidCpio - Cleaning /home/philip/rk3566/github/cfig/Android_boot_image_editor/build/unzip_boot/root ...
11:15:34:173 WARN AndroidCpio -   root/config has improper file mode 555, fix it
11:15:35:016 INFO AndroidCpio - cpio trailer found, mode=000001ed
11:15:35:017 INFO Common -  ramdisk extracted : build/unzip_boot/ramdisk.img -> build/unzip_boot/root
11:15:35:028 INFO DTC - parsing DTB: build/unzip_boot/dtb
11:15:35:042 INFO DTC - [dtc, -q, -I, dtb, -O, dts, build/unzip_boot/dtb, -o, build/unzip_boot/dtb.src]
11:15:35:065 INFO DTC - [dtc, -q, -I, dts, -O, yaml, build/unzip_boot/dtb.src, -o, build/unzip_boot/dtb.src.yaml]
11:15:35:066 INFO AVBInfo - parseFrom(boot.img) ...
11:15:35:091 INFO AVBInfo - boot.img: Glance(footer=Footer(versionMajor=1, versionMinor=0, originalImageSize=102600704, vbMetaOffset=102600704, vbMetaSize=704), vbMetaOffset=102600704).footer
11:15:35:176 INFO AVBInfo - VBMeta: boot.img -> build/unzip_boot/boot.avb.json
11:15:35:228 INFO BootV2 - 
                        Unpack Summary of boot.img
┌───────────────────────────────────────┬──────────────────────────────────────┐
│What                                   │Where                                 │
└───────────────────────────────────────┴──────────────────────────────────────┘
┌───────────────────────────────────────┬──────────────────────────────────────┐
│image info                             │build/unzip_boot/boot.json            │
├───────────────────────────────────────┼──────────────────────────────────────┤
│AVB info [verified]                    │build/unzip_boot/boot.avb.json        │
├───────────────────────────────────────┼──────────────────────────────────────┤
│kernel                                 │build/unzip_boot/kernel               │
│\-- version [4.19.193]                 │build/unzip_boot/kernel_version.txt   │
│\-- config                             │build/unzip_boot/kernel_configs.txt   │
├───────────────────────────────────────┼──────────────────────────────────────┤
│ramdisk                                │build/unzip_boot/ramdisk.img.gz       │
│\-- extracted ramdisk rootfs           │build/unzip_boot/root                 │
├───────────────────────────────────────┼──────────────────────────────────────┤
│second bootloader                      │build/unzip_boot/second               │
├───────────────────────────────────────┼──────────────────────────────────────┤
│recovery dtbo                          │build/unzip_boot/recoveryDtbo         │
├───────────────────────────────────────┼──────────────────────────────────────┤
│dtb                                    │build/unzip_boot/dtb                  │
│\-- decompiled dts                     │build/unzip_boot/dtb.src              │
└───────────────────────────────────────┴──────────────────────────────────────┘
11:15:35:293 WARN PackableLauncher - 'unpack' sequence completed

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 2m 58s
10 actionable tasks: 10 executed
`

and pack
`
> Task :pack
11:16:25:270 WARN PackableLauncher - [boot.img] will be handled by [BootImgParser]
11:16:25:358 WARN PackableLauncher - 'pack' sequence initialized
11:16:25:365 INFO BootImgParser - Loading config from build/unzip_boot/boot.json
11:16:25:545 INFO Common - Deleting build/unzip_boot/ramdisk.img.gz ...
11:16:25:553 INFO Common - Deleting build/unzip_boot/ramdisk.img ...
11:16:25:577 INFO Common - Packing rootfs build/unzip_boot/root ...
11:16:25:594 INFO AndroidCpio - loading build/unzip_boot/ramdisk.img_filelist.txt
11:16:35:990 INFO ZipHelper - compress(gz) done: build/unzip_boot/ramdisk.img.gz
11:16:35:990 INFO Common - build/unzip_boot/ramdisk.img.gz is ready
11:16:35:996 WARN BootV2 - using fake recoveryDtboOffset 102475776 (as is in AOSP avbtool)
11:16:36:597 INFO BootV2 - Writing data ...
11:16:37:398 INFO BootV2 - [aosp/system/tools/mkbootimg/mkbootimg.py, --header_version, 2, --base, 0x0, --kernel, build/unzip_boot/kernel, --kernel_offset, 0x10008000, --ramdisk, build/unzip_boot/ramdisk.img.gz, --ramdisk_offset, 0x11000000, --second, build/unzip_boot/second, --second_offset, 0x10f00000, --recovery_dtbo, build/unzip_boot/recoveryDtbo, --dtb, build/unzip_boot/dtb, --dtb_offset, 0x11f00000, --pagesize, 2048, --cmdline, androidboot.wificountrycode=CN androidboot.hardware=rk30board androidboot.console=ttyFIQ0 firmware_class.path=/vendor/etc/firmware init=/init rootwait ro init=/init androidboot.selinux=permissive buildvariant=userdebug, --os_version, 11.0.0, --os_patch_level, 2021-09-00, --tags_offset, 0x10000100, --id, --output, boot.img.google]
0xbe3b8b45d88fa95b1312967ca414ce6648d3b866000000000000000000000000
11:16:38:871 INFO Common - boot.img.clear hash a07c34ab56bb99e861e7b0c05cd3684f5ca5ea59, boot.img.google hash a07c34ab56bb99e861e7b0c05cd3684f5ca5ea59
11:16:38:871 INFO Common - Hash verification passed: a07c34ab56bb99e861e7b0c05cd3684f5ca5ea59
11:16:38:873 INFO Signer - Adding hash_footer with verified-boot 2.0 style
11:16:39:184 INFO Avb - addHashFooter(boot.img.signed) ...
11:16:39:186 INFO Avb - max_image_size: 125759488
11:16:39:188 INFO Avb - original image boot.img.signed doesn't have AVB footer
11:16:39:194 INFO HashDescriptor - preset salt[32] is valid: 8a71f57d2c86833ca48b2c449b594beb4d91c05efe392a371f414f7fb3e7a2c9
11:16:39:194 INFO HashDescriptor - flag: use_ab = 1
11:16:40:281 INFO HashDescriptor - Digest(salt + file): abc3b65c9fc5babc424f4165d4e235a0465d431ba792c893e41a84e5f655fcc5
11:16:40:283 INFO Avb - updated hash descriptor:000000000000000200000000000000b800000000061d9000736861323536000000000000000000000000000000000000000000000000000000000004000000200000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000626f6f748a71f57d2c86833ca48b2c449b594beb4d91c05efe392a371f414f7fb3e7a2c9abc3b65c9fc5babc424f4165d4e235a0465d431ba792c893e41a84e5f655fcc5
11:16:40:285 INFO AuxBlob - encodePubKey(): No key to encode for algorithm NONE
11:16:40:285 INFO AuxBlob - no pubkey in auxBlob
11:16:40:285 INFO AuxBlob - no pubkey metadata in auxBlob
11:16:40:286 INFO AuxBlob - encodePubKey(): No key to encode for algorithm NONE
11:16:40:290 INFO AVBInfo - pkmd size: 0, pkmd offset : 416
11:16:40:291 INFO AuthBlob - No auth blob for algorithm NONE
11:16:40:291 INFO AuxBlob - encodePubKey(): No key to encode for algorithm NONE
11:16:40:291 INFO AuxBlob - no pubkey in auxBlob
11:16:40:291 INFO AuxBlob - no pubkey metadata in auxBlob
11:16:40:291 INFO AuxBlob - encodePubKey(): No key to encode for algorithm NONE
11:16:40:291 INFO AVBInfo - pkmd size: 0, pkmd offset : 416
11:16:40:292 INFO AuthBlob - No auth blob for algorithm NONE
11:16:40:301 INFO Avb - Footer(versionMajor=1, versionMinor=0, originalImageSize=102600704, vbMetaOffset=102600704, vbMetaSize=704)
11:16:40:302 INFO Avb - 1/4 Padding image with 0 bytes ...
11:16:40:304 INFO Avb - 2/4 Appending vbmeta (4096 bytes)...
11:16:40:304 INFO Avb - 3/4 Appending DONT CARE CHUNK (23220224 bytes) ...
11:16:40:341 INFO Avb - 4/4 Appending AVB footer (4096 bytes)...
11:16:40:342 INFO Avb - addHashFooter(boot.img.signed) done.
11:16:40:347 INFO Signer - [aosp/avb/avbtool.v1.2.py, add_hash_footer, --image, boot.img.signed2, --flags, 0, --partition_size, 125829120, --salt, 8a71f57d2c86833ca48b2c449b594beb4d91c05efe392a371f414f7fb3e7a2c9, --partition_name, boot, --hash_algorithm, sha256, --algorithm, NONE, --rollback_index, 0, --prop, com.android.build.boot.fingerprint:TOSCIDO/T201-EEA/T201-EEA:11/RP1A.201105.002/ysq20210322:user/release-keys, --prop, com.android.build.boot.os_version:11, --internal_release_string, avbtool 1.1.0]
11:16:42:340 INFO Common - boot.img.signed hash 528b1f13472ce98d153f52e724ad4be07e2c657a, boot.img.signed2 hash 528b1f13472ce98d153f52e724ad4be07e2c657a
11:16:42:340 INFO Common - Hash verification passed: 528b1f13472ce98d153f52e724ad4be07e2c657a
11:16:42:340 INFO BootV2 - Adding hash_footer with verified-boot 2.0 style
11:16:42:370 INFO VendorBoot - 
                        Pack Summary of boot.img
┌───────────────────────────────────────┬──────────────────────────────────────┐
│What                                   │Where                                 │
└───────────────────────────────────────┴──────────────────────────────────────┘
┌───────────────────────────────────────┬──────────────────────────────────────┐
│re-packed boot.img                     │boot.img.signed                       │
└───────────────────────────────────────┴──────────────────────────────────────┘
11:16:42:378 WARN PackableLauncher - 'pack' sequence completed

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 21s
13 actionable tasks: 4 executed, 9 up-to-date
`

**Comment by cfig** [comment]
can you attach the image file here? 
We may try to binary compare the original file with the repacked one.

**Comment by dieselnutjob** [comment]
The factory image is here (for now)
https://drive.google.com/file/d/1faWsQldtTA1lYVSTW6scb2jSV1d3ozgN/view?usp=sharing
I got this image simply by dumping the partition out of the device with dd

**Comment by cfig** [comment]
Yeah, the 'dd' way is what we usually do.
I renamed it to "boot.img", then "unpack" and "pack", the newly generated boot.img.signed (or boot.img.signed2) has the same md5 hash as original boot.img.

```
c34e13de291aef9d82b78dd24fe95fc8  boot.img
c34e13de291aef9d82b78dd24fe95fc8  boot.img.signed
c34e13de291aef9d82b78dd24fe95fc8  boot.img.signed2
```
I am using latest "master" branch.

**Comment by dieselnutjob** [comment]
I just tried again.
As you say, unpack then repack result in two files
c34e13de291aef9d82b78dd24fe95fc8  boot.img.signed
c34e13de291aef9d82b78dd24fe95fc8  boot.img.signed2
c34e13de291aef9d82b78dd24fe95fc8  mmcblk2p11.img

Most likely scenario: I made some stupid mistake
Second possibility: Something changed because I rebuilt my desktop yesterday (newer version of Lubuntu)

**Comment by cfig** [comment]
OK, then proceed happily ~
