### ISSUE TITLE
can not parse Galaxy S22+ vendor_boot image

### ISSUE THREAD

**Issue by cfig** [cfig/Android_boot_image_editor#86]

**Comment by cfig** [comment]
"dev" branch has fixed the `unpack` issue.
`pack` issue is still under checking ...

**Comment by cfig** [comment]
Fix merged to trunk. Can you try again if possible?

**Comment by kereng77** [comment]
It worked beautifully!! Thank you so much

**Comment by cfig** [comment]
Ha~
Good to hear that ~
