### ISSUE TITLE
The bug of unpack misc.img.

### ISSUE THREAD

**Issue by zhengjingjian** [cfig/Android_boot_image_editor#87]
Hi bro.Thanks for the new  support.I found a bug is that when I unpack the misc.img,the files are released to the main folder and the clean command is not good to used.Can you fix it?

**Comment by cfig** [comment]
OK, thanks for trying the unadvertised feature of misc.img. By now, misc.img is only for soc level feature study and verification.
But yes, I will refine the 'clean' command later.

**Comment by cfig** [comment]
gradle has an internal task called `clean`.
To avoid any confusion, I added another `clear` task to do project related clean up actions.

Parsed misc.img result is now placed at `build/unzip_boot/misc.json`.

**Comment by cfig** [comment]
Code updated, kindly have a try ~
